version: '3'
services:
  shopo_reverse_proxy:
    container_name: shopo_reverse_proxy
    image: nginx:1.23.0-alpine
    volumes:
      - ./conf.d/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db
      - rabbitmq
  db:
    container_name: myfit_postgres
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=vsyveniu
      - POSTGRES_PASSWORD=423ps4212
      - POSTGRES_DB=myFit
    ports:
      - 5432:5432
    volumes:
      - ./db_volume:/var/lib/postgreqsl/data
  rabbitmq:
    image: rabbitmq:3.10.5
    container_name: shopo_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
#  app:
#    container_name: myFit
#    image: node:16.16.0-alpine
#    volumes:
#      - ./:/home/node/app
#    working_dir: /home/node/app
#    command: "yarn rw dev"
#    depends_on:
#      - db
#    restart: always
#    ports:
#      - 9229:9229
#      - 8910:8910
