-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "fiber" DECIMAL(65,30),
ADD COLUMN     "sugar" DECIMAL(65,30),
ALTER COLUMN "carbohydrates" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "protein" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "fat" SET DATA TYPE DECIMAL(65,30);
